-- AlterTable
ALTER TABLE "Diet" ADD COLUMN IF NOT EXISTS "dailyFiberGoal" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN IF NOT EXISTS "isExported" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "DietLog" ADD COLUMN IF NOT EXISTS "waterIntake" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "coverExerciseId" TEXT,
ADD COLUMN IF NOT EXISTS "coverImageUrl" TEXT,
ADD COLUMN IF NOT EXISTS "goal" TEXT NOT NULL DEFAULT 'hipertrofia',
ADD COLUMN IF NOT EXISTS "isExported" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "isActive" SET DEFAULT false;

-- AlterTable
ALTER TABLE "Workout" ADD COLUMN IF NOT EXISTS "weekDay" TEXT;
